title: Some Stutter, Luh!
description: The Communication Collaborative is a research group in solidarity with The Newfoundland and Labrador Stuttering Association (NLSA) and those with speech, language and voice impairments living in the Canadian province of Newfoundland and Labrador. We are people who stutter (PWS), members of provincial government, members of the public, educators, speech-language pathologists, academic researchers, university students, mental health professionals, disability advocates, and NLSA members. For general inquiries about this podcast, click [here](mailto:info@somestutterluh.ca).<BR>
If you are person who stutters or lives with a communication challenge, or a parent / caregiver of someone who does, a speech-language pathologist, communication researcher, ally or a health care professional interested in being a guest on Some Stutter, Luh!, please [get in touch with our team](mailto:info@somestutterluh.ca).
author: by The Communication Collaborative
email: info@somestutterluh.ca
lang: en-us
copyright: "Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)"
logo: /assets/img/SSL-logo-season3.png
minimal_mistakes_skin: "air" # "default", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
