title: Some Stutter Luh!
description: Newfoundland and Labrador's first podcast about living with language disorders. We speak directly to people living with speech and language disorders, and others such as speech language pathologists, researchers, educators and family members. We use inclusive language and themes to help rebuild confidence and hope by dismantling myths, stigma, stereotypes and barriers.
author: a podcast by The Communication Collaborative
email: info@somestutterluh.ca
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 2021"
logo: /assets/img/SSL-logo-notitle.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
